#!/bin/bash

set -eux

#SSH_DIR=$HOME/.ssh
#SSH_KEY=${SSH_DIR}/id_rsa_github
#
#mkdir -p "${SSH_DIR}"
#echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" >> $SSH_DIR/config
#echo -n "${GIT_PRIVATE_KEY:?}" > "${SSH_KEY}"
#chmod 0600 "${SSH_KEY}"
#
#eval $(ssh-agent)
#ssh-add "${SSH_KEY}"

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_DIR="$(cd "${CURRENT_DIR}/../.." && pwd)"
ORIGINAL_DEPLOYMENT_DIR="${WORKSPACE_DIR}/deployment-configuration"
UPDATED_DEPLOYMENT_DIR="${WORKSPACE_DIR}/updated-cf-mysql-deployment-release-candidate"
MANIFEST_OUTPUT_DIR="${WORKSPACE_DIR}/updated-deployment-manifest"

function configure_git() {
  git config --global user.name "${GIT_AUTHOR_NAME:?}"
  git config --global user.email "${GIT_AUTHOR_EMAIL:?}"
}

function prepare_outputs() {
  git clone deployment-configuration updated-cf-mysql-deployment-release-candidate
}

function install_update_manifest_releases() {
  mkdir -p "${WORKSPACE_DIR}/go/src/github.com/cloudfoundry"
  ln -s "${WORKSPACE_DIR}/runtime-ci" "${WORKSPACE_DIR}/go/src/github.com/cloudfoundry/runtime-ci"
  export GOPATH="${WORKSPACE_DIR}/go"
  export PATH="$GOPATH/bin":$PATH

  go install github.com/cloudfoundry/runtime-ci/util/update-manifest-releases
}

function copy_bosh_io_release_info_to_manifest() {
  install_update_manifest_releases

  ORIGINAL_DEPLOYMENT_MANIFEST_PATH=cf-mysql-deployment.yml \
  UPDATED_DEPLOYMENT_MANIFEST_PATH=cf-mysql-deployment.updated.yml \
  update-manifest-releases -build-dir "${WORKSPACE_DIR}" -release cf-mysql
}

function commit_changes_to_release_candidate() {
  pushd "${UPDATED_DEPLOYMENT_DIR}" > /dev/null
    cp "${MANIFEST_OUTPUT_DIR}/cf-mysql-deployment.updated.yml" cf-mysql-deployment.yml
    git add cf-mysql-deployment.yml
    git commit -m "$(cat "${WORKSPACE_DIR}/commit-message") [skip ci]"
  popd > /dev/null
}

#pushd "${DEPLOYMENT_DIR}"
#
#  git checkout release-candidate
#  git checkout -b "v${VERSION}"
#
#  copy_bosh_io_release_info_to_manifest
#
#  git add cf-mysql-deployment.yml
#  git commit -m "Bump version of cf-mysql-release in cf-mysql-deployment.yml"
#
#  git checkout develop
#  git merge "${VERSION_BRANCH}"
#  git checkout master
#  git merge develop
#
#  #Tags the head of the branch
#
#  git tag "v${VERSION}"
#
#
##git push origin :${TAG}
#popd


copy_bosh_io_release_info_to_manifest
configure_git
prepare_outputs
commit_changes_to_release_candidate

echo "for inspection"
exit 1

